Traceback (most recent call last):
  File "C_num.py", line 43, in <module>
  File "C:\Python34\lib\tkinter\__init__.py", line 2156, in __init__
    Widget.__init__(self, master, 'button', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2086, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: can't invoke "button" command: application has been destroyed
Traceback (most recent call last):
  File "C_num.py", line 43, in <module>
  File "C:\Python34\lib\tkinter\__init__.py", line 2156, in __init__
  File "C:\Python34\lib\tkinter\__init__.py", line 2086, in __init__
_tkinter.TclError: can't invoke "button" command: application has been destroyed
